# Module manifest for module 'SolarWinds.ServiceDesk'
# Generated by: David Stein
# Generated on: 4/23/2025

@{
    RootModule        = 'SolarWinds.ServiceDesk.psm1'
    ModuleVersion     = '1.0.2'
    # CompatiblePSEditions = @()
    GUID              = '15d2bfff-ebc1-4309-9aa1-51410f7ff8d3'
    Author            = 'David Stein'
    CompanyName       = 'Skatterbrainz'
    Copyright         = '(c) 2025 Skatterbrainz. All rights reserved.'
    Description       = 'SolarWinds Service Desk API Module - based on REST API reference https://apidoc.samanage.com/#section/General-Concepts'
    PowerShellVersion = '5.1'
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules   = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @('Connect-*', 'Get-*', 'New-*', 'Add-*', 'Set-*', 'Update-*', 'Export-*', 'Remove-*')
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData = @{
        PSData = @{
            Tags = @('ServiceDesk', 'SolarWinds', 'SWSD', 'samanage', 'HelpDesk', 'Incidents', 'Service', 'Tickets', 'Tasks', 'skatterbrainz')
            LicenseUri = 'https://github.com/Skatterbrainz/SolarWinds.ServiceDesk/LICENSE'
            ProjectUri = 'https://github.com/Skatterbrainz/SolarWinds.ServiceDesk'
            # IconUri = ''
            ReleaseNotes = 'This module is not produced by SolarWinds and is not supported by them. It is a community module that provides a PowerShell interface to the SolarWinds Service Desk API.'
            # Prerelease = ''
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}