# Module manifest for module 'SolarWinds.ServiceDesk'
# Generated by: David Stein
# Generated on: 2/2/2025

@{
    RootModule        = 'SolarWinds.ServiceDesk.psm1'
    ModuleVersion     = '1.0.0'
    # CompatiblePSEditions = @()
    GUID              = '15d2bfff-ebc1-4309-9aa1-51410f7ff8d3'
    Author            = 'David Stein'
    CompanyName       = 'Skatterbrainz'
    Copyright         = '(c) 2025 Skatterbrainz. All rights reserved.'
    Description       = 'SolarWinds Service Desk API Module'
    PowerShellVersion = '5.1'
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    RequiredModules   = @('PowerHTML')
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @('Connect-*', 'Get-*', 'New-*', 'Set-*', 'Update-*', 'Export-*', 'Remove-*')
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags = @('SolarWinds', 'ServiceDesk', 'HelpDesk', 'Incidents', 'Service', 'Tickets', 'skatterbrainz')
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
            # Prerelease = ''
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}